[feat] Home View 구현
SOPT-all/35-COLLABORATION-ANDROID-KAKAOWEBTOON pull request #24
Opened 2024-11-23 04:09 UTC by jm991014

## Related issue 🛠
- closed #18 

## Work Description ✏️
- Home View에 사용되는 Component 구현
- Home Screen 구현
- Home ViewModel 구현

## Screenshot 📸
https://github.com/user-attachments/assets/0b0c99cb-7678-4da1-a0a2-b55f6cbacede

## Uncompleted Tasks 😅
- [ ] HomeScreen에 `HomeFilter` 객체 Constraints로 이동
- [ ] ViewModel에 `selectedDay` 값을 `KakaoWebtoonIndicator`에 반영 할 지 말 지 결정
- [ ] TopBar 수정사항 반영하기

## To Reviewers 📢
HomeScreen 코드 보시면.. LazyColumn 안에서 webtoonList를 3칸씩 나누어서 보여주고 있는데...
```Kotlin
repeat(3 - urlChunk.size) {
    HomeCardEmptyView(
        modifier = Modifier
            .weight(1f)
            .height(260.dp)
    )         
}
```
여기 무슨 짓을 해도 고정 값을 주지 않으면 높이 설정이 안되는데 해결 법 아시는 분...

2024-11-25 04:16 UTC, t1nm1ksun requested changes
pr에 물어보신거 남겨두었습니다!
고생 많으셨어요!!!

2024-11-25 04:16 UTC, t1nm1ksun commented on app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/HomeScreen.kt
> +                            .height(260.dp)
pr에 남겨주신 질문사항 봤습니다!
걱정하시는 것처럼 높이에 고정값을 주게된다면 기기 크기가 달라졌을때 HomeCardView높이와 HomeCardEmptyView의 높이가 달라질것으로 예상됩니다, 그렇기 때문에 HomeCradView의 높이를 동적으로 측정해서 해당 값을 HomeCardEmptyView의 높이로 할당한다면 기기대응이 가능할 것 같습니다! 
(사실 HomeCardView의 높이를 Row의 높이로 고정시키고 그걸 가득채우는 로직이 좋을 것 같은데 잘 안되네요. .ㅠ)

`    var homeCardHeight by remember { mutableIntStateOf(0) }
`

해당 변수를 HomewScreem함수 상단에 선언해주시고 아래 사진처럼 사용하시면...!

<img width="620" alt="image" src="https://github.com/user-attachments/assets/acddbd24-45ad-4666-816c-a41f7e08e27b">

짜잔!

<img width="330" alt="image" src="https://github.com/user-attachments/assets/a1b85111-5b8c-4eb0-a6f4-b42a3ec57d9a">

2024-11-25 04:16 UTC, t1nm1ksun commented on app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/HomeViewModel.kt
> +    }
해당 내용 기획측이랑 이야기 해봤을때 일단 신작, 완결로는 시작이 안되게 해달라고 하셨습니다! 저희 구현사항에 요일 필터링이 없기 때문에 추후에 리소스가 남는다면 현재 요일로 설정하면 좋을 것 같아요!

2024-11-25 04:16 UTC, t1nm1ksun commented on app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeBanner.kt
> +            .clip(RoundedCornerShape(0.dp, 0.dp, 12.dp, 12.dp))
```suggestion
            .clip(RoundedCornerShape(topStart = 0.dp, topEnd =  0.dp, bottomEnd = 12.dp, bottomStart = 12.dp))
```
name argument 사용해주시면 가독성 측면에서 더 좋을 것 같습니다!

2024-11-25 04:16 UTC, t1nm1ksun commented on app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeBanner.kt
> +        )
```suggestion
        Text(
            text = stringResource(R.string.home_banner_button_title),
            style = KakaoWebtoonTheme.typography.body2Regular,
            color = KakaoWebtoonTheme.colors.white
        )
        Spacer(modifier=Modifier.width(4.dp))
```
Spacer와 padding을 사용하는 기준이 있으신가요? (저도 명예오비분한테 받았던 리뷰 인데요!)
저는 영역을 확정할 때 보통 padding을 사용하는 편이고 이런 경우는 Spacer를 사용합니다! 추후에 값이 변경되었을 때 찾기 쉬울 것 같아서요..! 
근데 갠취라 변경하실 필요는 없고 궁금해서 여쭤봅니다!

2024-11-25 04:16 UTC, t1nm1ksun commented on app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeFilterTextButton.kt
> +        ),
둘다 4.dp 같아요!

<img width="290" alt="image" src="https://github.com/user-attachments/assets/10516d33-d9ed-41c8-a364-2a2bc66d7700">

2024-11-25 04:16 UTC, t1nm1ksun commented on app/src/main/res/values/strings.xml
> +    <string name="home_footer_copyright">© KAKAO WEBTOON</string>
우와 동그라미c 어떻게 쓴거에요? ㅋㅋ

2024-11-25 04:16 UTC, t1nm1ksun commented on app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeFooter.kt
> +        }
```suggestion
        val footerItems = listOf(
        R.string.home_footer_private_policy,
        R.string.home_footer_terms_of_use,
        R.string.home_footer_customer_service,
        R.string.home_footer_business_information
    )

    Row(
        modifier = Modifier.padding(2.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(4.dp)
    ) {
        footerItems.forEachIndexed { index, stringResId ->
            Text(
                text = stringResource(stringResId),
                style = KakaoWebtoonTheme.typography.body4SemiBold,
                color = KakaoWebtoonTheme.colors.grey2
            )
            if (index != footerItems.lastIndex) {
                Icon(
                    imageVector = ImageVector.vectorResource(R.drawable.ic_home_vertical_line),
                    contentDescription = null,
                    tint = KakaoWebtoonTheme.colors.grey5
                )
            }
        }
    }
```
이렇게 까지 하는건 투머친가? ㅋㅋ

2024-11-25 04:16 UTC, t1nm1ksun commented on app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeGenreTabRow.kt
> +}
아직 디벨롭에 머지는 안됐지만 제가 만들어둔 modifier 확장함수 사용하시면 편하실 것 같아요

<img width="743" alt="image" src="https://github.com/user-attachments/assets/3d9d7ff9-9381-4b6e-8d89-08a648f95409">

### 이렇게 쓰시면 됩니당

<img width="565" alt="image" src="https://github.com/user-attachments/assets/6ba706b7-a6a9-4c65-b8d9-eb1cd2314253">

(Text나 Icon에도 사용 가능!)

2024-11-25 11:55 UTC, MinseoSONG approved these changes
굿입니다용 ~

2024-11-25 13:58 UTC, jm991014 commented on app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/HomeScreen.kt
> +                            .height(260.dp)
감사합니다!!

2024-11-25 13:58 UTC, jm991014 commented on app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeBanner.kt
> +            .clip(RoundedCornerShape(0.dp, 0.dp, 12.dp, 12.dp))
반영하겠습니다~!!!

2024-11-25 14:00 UTC, jm991014 commented on app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeBanner.kt
> +        )
이건 제가 변경하겠습니다~ 갠취여도 통일하는게 좋으니까요

2024-11-25 14:02 UTC, jm991014 commented on app/src/main/res/values/strings.xml
> +    <string name="home_footer_copyright">© KAKAO WEBTOON</string>
그냥 복붙했슴다 ㅋ

2024-11-25 14:02 UTC, jm991014 commented on app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeFooter.kt
> +        }
이게 가독성이 훨씬 좋네요ㅋ

2024-11-25 14:09 UTC, jm991014 commented on app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeGenreTabRow.kt
> +}
반영했습니다~!!

2024-11-25 14:11 UTC, jm991014 commented on app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/HomeViewModel.kt
> +    }
기획쪽에서 신작/완결로 시작이 안되게 해달라고 하셨단 건, 특정 **요일**로 시작하게 해달라 하셨단 말씀인거죠?
그렇다면 API 상으로 **요일**을 path로 받게 되어 있던데 현재 요일로 설정해야 하는거 아닌가요..?
제가 잘못이해한걸까요 ㅜㅜ

2024-11-26 03:07 UTC, t1nm1ksun approved these changes
반영하셨으면 머지하셔도 될거같아요! 
고생하셨습니다!

2024-11-26 03:54 UTC, merged